# Generated by Django 4.2.2 on 2023-06-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate_text',
            field=models.CharField(default='FFFFF', max_length=5),
        ),
    ]
