# Generated by Django 4.2.2 on 2023-06-11 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
