# Generated by Django 4.2.2 on 2023-06-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_testimonials'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='testimonials',
            new_name='testimonial',
        ),
    ]
