# Generated by Django 4.2.2 on 2023-06-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='null_from_django', max_length=100),
            preserve_default=False,
        ),
    ]
