# Generated by Django 4.2.2 on 2023-06-12 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_confirmed_orders_delete_confirmed_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_orders',
            name='total_price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
