# Generated by Django 4.2.2 on 2023-06-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_rename_username_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_orders',
            name='orders',
            field=models.ManyToManyField(to='store.order'),
        ),
    ]
