# Generated by Django 4.2.2 on 2023-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_remove_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmed_orders',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
