# Generated by Django 4.2.2 on 2023-06-16 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_confirmed_orders_is_delivered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmed_orders',
            name='status',
        ),
    ]
