# Generated by Django 4.2.2 on 2023-06-17 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_confirmed_orders_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmed_orders',
            name='status',
        ),
    ]
