# Generated by Django 4.2.2 on 2023-06-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_confirmed_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/product-null.jpg', upload_to='static/images/'),
        ),
    ]
