# Generated by Django 4.2.2 on 2023-06-17 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_alter_product_gallery_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gallery_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
