# Generated by Django 4.2.2 on 2023-06-17 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_product_gallery_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='gallery_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gallery_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gallery_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gallery_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='offer_image',
        ),
    ]
