# Generated by Django 4.2.2 on 2023-06-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_remove_product_gallery_1_remove_product_gallery_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gallery_1',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_2',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_3',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='gallery_4',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/product-null.jpg', upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='offer_image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/'),
        ),
    ]
